# Configuration parameters for data recording node.

output_directory: '/onav_log/rosbag_data'

topics:
  - '/rosout_agg/(.*)'
  - '/rosout'
  - '/twist_marker_server/(.*)'
  - '/localization_helper/(.*)'
  - '/localization_core/(.*)'
  - '/navigation/(.*)'
  - '/piksi_position/(.*)'
  - '/piksi_heading/(.*)'
