# Configuration parameters for data recording node.

output_directory: '/opt/onav/rosbag_data'

topics:
  - '/rosout_agg/(.*)'
  - '/rosout'
  - '/twist_marker_server/(.*)'
  - '/autonomy/(.*)'
  - '/dock/(.*)'
  - '/laser_target_tracker/(.*)'
  - '/localization/(.*)'
  - '/localization_core/(.*)'
  - '/localization_helper/(.*)'
  - '/mission/(.*)'
  - '/navigation/(.*)'
  - '/onboard_systems/(.*)'
  - '/platform/(.*)'
  - '/swiftnav/(.*)'
  - '/sensors/gps(.*)'
  - '/sensors/imu(.*)'
  - '/target/(.*)'
  - '/tf(.*)'
